#!/usr/bin/env ruby

def simplify(rx)
  rx
    .gsub("0?*", "0*")
    .gsub("0?0*", "0*")
    .gsub("0*0?", "0*")
    .gsub("(0*|0?)", "0*")
    .gsub("(20*|2)", "20*")
    .gsub("(10*|1)", "10*")
    .gsub("(20*1|0?)*", "(20*1|0)*")
    .gsub("(0*1|1)", "0*1")
    .gsub("(0*2|2)", "0*2")
end

states = [0, 1, 2]
transitions = {
  [0,0] => "0?",
  [1,1] => "0?",
  [2,2] => "0?",
  [0,1] => "1",
  [1,2] => "1",
  [2,0] => "1",
  [0,2] => "2",
  [2,1] => "2",
  [1,0] => "2",
}

states.each do |k|
  new_transitions = {}
  states.each do |i|
    states.each do |j|
      a = transitions[[i,k]]
      b = transitions[[k,k]]
      c = transitions[[k,j]]
      d = transitions[[i,j]]
      new_transitions[[i,j]] = simplify("(#{a}#{b}*#{c}|#{d})")
    end
  end
  transitions = new_transitions
end

pp transitions
