#!/usr/bin/env python3

def override(value, condition):
  def decorator(func):
    def wrapper(*args, **kwargs):
      if condition(*args, **kwargs):
        return value
      else:
        return func(*args, **kwargs)
    return wrapper
  return decorator

@override("FizzBuzz", lambda i: i%15 == 0)
@override("Buzz", lambda i: i%5 == 0)
@override("Fizz", lambda i: i%3 == 0)
def fizzbuzz(i):
  return str(i)

for i in range(1,101):
  print(fizzbuzz(i))
